FROM  php:7.2-apache

LABEL Vendor="Actilis" \
      Maintener="Francois MICAUX <dok-images@actilis.net>" \
      License=GPLv3 \
      Version=2018.09-debian-phpfpm

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    git  \
    curl \
    unzip

# Install PHP-modules not included in base httpd-php image
RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get -y install libpng-dev libfreetype6-dev libjpeg62-turbo-dev zlib1g-dev libzip-dev libldap-dev libicu-dev libc-client-dev libkrb5-dev \
 && docker-php-ext-configure imap --with-kerberos --with-imap-ssl && docker-php-ext-install imap \
 && docker-php-ext-configure intl && docker-php-ext-install intl \
 && docker-php-ext-configure zip --with-libzip && docker-php-ext-install mbstring zip gd \
 && docker-php-ext-install ldap \
 && docker-php-ext-install mysqli \
 && docker-php-ext-install pdo_mysql \
 && rm -r /var/lib/apt/lists/

# Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
 && php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo     'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
 && php composer-setup.php \
 && php -r "unlink('composer-setup.php');" \
 && mv composer.phar /usr/local/bin/composer


# Files to serve (testing)
COPY files/var  /var

# Manage permisisons, clean...
RUN chmod o+x /var /var/www \
 && chown -R www-data.www-data /var/www/html \
 && chmod -R 755 /var/www/html 

# Enable apache2-modules
RUN a2enmod rewrite

# Use EP from origin image
# ========================
# ENTRYPOINT ["docker-php-entrypoint"]
# CMD ["apache2-foreground"]

