FROM  alpine:edge

LABEL Vendor="Actilis" \
      Maintener="Francois MICAUX <dok-images@actilis.net>" \
      License=GPLv3 \
      Version=2018.05-alpine

# Installation Apache + PHP + modules de PHP nécessaires
RUN apk add --no-cache \
	bash \
        apache2 apache2-proxy apache2-utils \
	php7-fpm \
        supervisor

# Données à importer (ADD, COPY,...)
COPY files/  /

# Manage permisisons, clean...
RUN rm -f /etc/httpd/conf.d/welcome.conf \
 && chmod  o+x /var /var/www \
 && chown -R apache.apache /var/www/html \
 && chmod -R 750 /var/www/html 

# Ports ?
EXPOSE 80

# Définition de l'entrypoint (ou CMD pendant les tests...)
ENTRYPOINT ["/httpd-entrypoint.sh"]
CMD ["/usr/bin/supervisord","-c","/etc/supervisord.conf"]

