FROM  alpine:edge

LABEL Vendor="Actilis" \
      Maintener="Francois MICAUX <dok-images@actilis.net>" \
      License=GPLv3 \
      Version=2018.05-alpine-phpfpm

# Installation Apache + PHP + modules de PHP nécessaires
RUN apk add --no-cache bash apache2-proxy apache2-utils php7-fpm php7-session supervisor

# Données à importer (ADD, COPY,...)
COPY files/  /

# Manage permisisons, clean...
RUN chmod o+x /var /var/www \
 && chown -R apache.apache /var/www/html \
 && chmod -R 755 /var/www/html 

# Ports 
EXPOSE 80

# Entrypoint does the HTTPD configuration
ENTRYPOINT ["/httpd-entrypoint.sh"]
